version: '3.7'

services:
  server:
    image: "node"
#    build:
#      context: .
#      dockerfile: Dockerfile
    command: 'node /root/server.js'

    volumes:
      - ./:/root/

    ports:
      - 8080:8080
      - 8081:8081
    healthcheck:
      test: curl -sS http://127.0.0.1:8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

    deploy:
      restart_policy:
        condition: on-failure